### ISSUE TITLE
Fails to build with python3

### ISSUE THREAD

**Issue by yurivict** [bdarcus/citeproc-py#2]
Getting this error on FreeBSD 11.1 using python-3.6:
```
Assume we are running from a source distribution.
running build
running build_py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 128, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 74, in run
    convert_rnc()
  File "setup.py", line 67, in convert_rnc
    root = rnc2rng.load(rnc)
  File "/usr/local/lib/python3.6/site-packages/rnc2rng/__init__.py", line 4, in load
    return parser.parse(f=f)
  File "/usr/local/lib/python3.6/site-packages/rnc2rng/parser.py", line 559, in parse
    fn, src = f.name, f.read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 19994: ordinal not in range(128)

```

**Comment by bdarcus** [comment]
I never finished this, and haven't touched the code in years. I left it here should someone else want to run with it.

**Comment by yurivict** [comment]
This project is a dependency for something else, this is why I needed to create the FreeBSD port for it.

**Comment by bdarcus** [comment]
Ah, I think you may be thinking about another similarly named project?

I should probably rename this to remove potential for confusion.

**Comment by bdarcus** [comment]
Maybe this one?

https://github.com/brechtm/citeproc-py

**Comment by yurivict** [comment]
You are right: the name ```citeproc-py``` leads to this PyPi URL: https://pypi.org/project/citeproc-py/ which points to https://github.com/brechtm/citeproc-py

**Comment by yurivict** [comment]
Sorry for this confusion!
